### ISSUE TITLE
Tags from <head> appearing in <body>

### ISSUE THREAD

**Issue by DaniellMesquito** [Software-js/WS.js#76]
This occurs because `<head>` have `<div>` elements, what makes Chrome mix all `<head>`'s tags in `<body>` structure. WTF do it, Chrome?!

**Comment by DaniellMesquita** [comment]
I can fix it by making inline javascript generate all needed boot objects above <body> structure.

**Comment by DaniellMesquito** [comment]
Fixed in the new Addons/Boot systems.
